Return correct type when filtering out cookbooks from graph
When running `chef install` and there are two cookbook sources that have
a cookbook of the same name, there would be an implicit nil return when
filtering that cookbook from the graph, which would lead to:

```
Error: Failed to generate Policyfile.lock
Reason: (NoMethodError) undefined method `each' for nil:NilClass
```

...when generating the Solve::Graph. Returning an empty Hash causes the
coobkook to be omitted from the Solve::Graph, which is what we want.